on:
    merge_group:
        types: [checks_requested]
    pull_request:

jobs:
    test:
        environment: test-env
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
            - run: echo $((${{secrets.TEST_SECRET_2}} + ${{secrets.TEST_SECRET_2}}))
              if: ${{github.event_name}} == 'pull_request'
